apiVersion: v1
kind: Service
metadata:
  name: helloworld-v1
spec:
  type: LoadBalancer
  ports:
  - port: 8050
    nodePort: 30303
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: helloworld-v1
